### PR TITLE
Use setting directly to avoid Django nag about creating migrations wh…

### PR DESCRIPTION
**Pull request by mrmachine**
…en using a `SITE_ID` other than `1`.

### CODE REVIEW

**Comment by stephenmcd** [comment]
Isn't the reverse true - you'd get asked to create a migration each time the SITE_ID settings changes if we don't just use 1?

**Comment by mrmachine** [comment]
Nope. Django freezes everything about models now, not only attributes that impact the database. If a default is serialised to `1` because the person who created the migration had `SITE_ID=1`, then I run `migrate` with `SITE_ID=2`, Django will tell me to run `makemigrations` which will then freeze it at `2`.

To confirm, just add `SITE_ID=2` to your settings and run `makemigrations`.

By using the setting directly, as opposed to the value of the setting at the time the migration was created, the current and previously frozen value will always be the same, and there will be no need for a new migration.

The default isn't actually a database default, so changing the setting won't break anything for previously applied migrations or data.

**Comment by stephenmcd** [comment]
Oh, cool - didn't know that.

Thanks a lot!

**Comment by stephenmcd** [comment]
Oh I see now! I didn't read the commit properly and just thought you were changing the default on the model. I see it's the migration using the setting - that's clever and makes sense. :-)

**Pull request merged**
