### PR TITLE
Don't require an old version of `future` that might conflict with oth…

### PR DESCRIPTION
**Pull request by mrmachine**
…er installed package requirements.

### CODE REVIEW

**Comment by stephenmcd** [comment]
Let's pin it to what the latest version is right now - leaving it open like that is a recipe for breakage.

**Comment by stephenmcd** [comment]
I've done it here 1607ea0a06dfd23154b5fe6777ad8ac5b99ce291

**Comment by mrmachine** [comment]
I think the opposite is true. Pinning it in `setup.py` is a recipe for version conflicts with other packages, either now or in the future. Requirements in `setup.py` should be as abstract as possible. They should allow everything except specific versions or version ranges that are known NOT to work with your package, to minimise the possibility of a version conflict with another installed package.

For example, if you have it pinned at `0.15.0` (current right now), even though your package only really requires a feature introduced in 0.9`, your package cannot be installed alongside another package that works requires a feature that was removed in `0.14` (for example).

The projects that use your package should flatten and pin absolute requirements into a `requirements.txt` file in order to reproduce a known working environment, but individual packages should not require specific versions of their dependencies, only exclude those known not to work.

**Comment by stephenmcd** [comment]
What happens when someone's automated deployment breaks because it pulls in a newer version of `future` that's incompatible?

**Comment by mrmachine** [comment]
They can fix it in their own project by adding `future<0.15.X` to their `setup.py` (which still satisfies your package's `>=0.9`).

If it's your package that doesn't work with `0.15.X`, then they can submit a pull request that changes it to `>=0.9,<0.15.X`, and if it the problem with `0.15.X` was subsequently fixed in `0.16.0` then you could change it to `>=0.9,<0.15.X,>=0.16.0`.

Someone's automated deployment could just as easily break if another package required by their project specifies `future<0.15.0` or `future>0.15.0`, either of which would conflict with your package.

**Comment by stephenmcd** [comment]
I understand where you're coming from, opening up the requirement to allow newer versions to automatically be supported certainly makes things easier, but I've just seen this wreak havoc on commercial projects as well as with library maintenance too often in the past - what you're proposing is deferring the breakage until a later date, rather than controlling it up front.

If other packages require future and are pinned to an out of date version, then they can be brought up to date to match the latest, just like we've done here.

**Comment by mrmachine** [comment]
This is not right. It's not about deferring breakage until a later date. It's about completely avoiding a conflict (and breakage) that is not easily fixed without altering 3rd party code, which is not always quick to happen when the maintainer is on vacation or has abandoned the software.

The [Python Packaging User Guide](https://packaging.python.org/en/latest/requirements.html) says

> `install_requires` is a `setuptools` `setup.py` keyword that should be used to specify what a project **minimally** needs to run correctly.

and

> it’s best practice to indicate any known lower or upper bounds.

The takeaway from that sentence is **known** bounds. I think it would only be advisable to include an upper future bound when you know in advance that a project uses semantic versioning. For example, you might require `Django>=1.7,<1.9` because 1.9 is not out yet and you know it will remove features that have been deprecated in 1.7 which your package supports and your package has not yet removed its dependency on those features.

By pinning a dependency to a current version in `setup.py` and not allowing any future versions (that may or may not be compatible), you are guaranteeing breakage and work for yourself when someone wants to use your package along side another package that uses a newer version of the dependency which may well be compatible.

It's making an inter-package compatibility problem between your package and another package that might have nothing to do with yours and you have no interest in using or supporting, your problem to fix.

Unless the dependency in question is historically known to introduce backwards incompatible changes frequently, without regard for semantic versioning, then the default assumption should be for a re-usable library package such as `django-forms-builder` to allow future versions of its dependencies, and for projects (commercial or otherwise) that make use of it to flatten and pin their entire dependency tree (e.g. in a `requirements.txt` file) as part of their testing and automated deployment process.

That way they can avoid any breakage and you only need to update your library package when it's known to not work.

**Comment by mrmachine** [comment]
Forgot to include this other relevant comment from the Python Packaging User Guide:

> It is not considered best practice to use `install_requires` to pin dependencies to specific versions, or to specify sub-dependencies (i.e. dependencies of your dependencies). This is overly-restrictive, and prevents the user from gaining the benefit of dependency upgrades.

**Comment by stephenmcd** [comment]
Wish I could go back in time to when I had as much faith as you do in third party code :-)

Not sure what else to say here - my experience has been different than yours.

**Comment by mrmachine** [comment]
It shouldn't require any faith in 3rd party code, because users will have the power to resolve conflicts themselves at the project level if packages abstract requirements aren't overly restrictive.

I hope you're available and as quick to respond in future as you have been today, next time we add a package to our project that depends on `future>0.15` or `future<0.15`, and I hope that when you make that change for us, you don't break anyone else's projects :)

E.g. anyone who is already using your package in a project with any other version of `future` than `0.15.0` will have it upgraded to `0.15.0` at their next deployment, which may well break their project, when `django-forms-builder` doesn't actually require `0.15.0` at all. If your dependencies were left as less restrictive, existing package installs would only be upgraded if the developer did `pip install -U`.

**Comment by mrmachine** [comment]
I also note that you are using abstract/minimal version specifiers for other dependencies in `setup.py`, e.g.

```python
            "sphinx-me >= 0.1.2",
            "unidecode",
            "django-email-extras >= 0.2",
```

**Comment by stephenmcd** [comment]
Most of those aren't third party! 😉

**Comment by mrmachine** [comment]
Could you please update the release on PyPI as well? It's still requiring an old version of `future` which is causing version conflicts with other dependencies in my project.

**Comment by mrmachine** [comment]
Please reconsider the use of absolute versions in `setup.py`. There are two previously unconsidered things that make it problematic:

1. `pip` appears to resolve sub-dependency version conflicts in "first found, wins" order (see: https://github.com/pypa/pip/issues/988). That means if my `setup.py` requires another package that also depends on `future` (e.g. `django-fluent-pages`) and it appears before `django-forms-builder`, the version installed into my virtualenv will almost certainly not be the one required by `django-forms-builder`.

2. Scripts that are installed via `setup.py` strictly enforce their dependency requirements at runtime. This makes it literally impossible to execute such a script if any other package requires `future>0.15.0` or `future<0.15.0`, even if I override the sub-dependency conflict by explicitly requiring `future==0.15.0` in my `setup.py`. It's also fiddly and error prone if the other package requires a minimum or maximum version that doesn't conflict with `django-forms-builder`, because I'll need to make sure that `django-forms-builder` appears first in my `setup.py`.

Here's an example `setup.py`:

```python
import setuptools

setuptools.setup(
    name='foo',
    version='0.1',
    packages=setuptools.find_packages(),
    install_requires=[
        'django-fluent-pages',
        'django-forms-builder',

        # Ensure that absolute `future` dependency from `django-forms-builder`
        # is not clobbered by minimum dependency from other packages (e.g.
        # `django-fluent-pages`). See: https://github.com/pypa/pip/issues/988
        'future==0.15.0',

        # If I don't do this, a newer version than 0.15.0 will be installed
        # because `django-fluent-pages` appears before `django-forms-builder`,
        # and while I can override conflicting sub-dependency requirements
        # here, the sub-dependency requirements are still enforced when
        # executing scripts (e.g. `foo.py`, below).

        # Therefore, I must specify a version that is explicitly compatible
        # with all the dependencies above.

        # As soon as another dependency requires `future<0.15.0` or
        # `future>0.15.0`, this will break scripts in a way that cannot be
        # resolved in `setup.py`. Instead, I will have to remove
        # `django-forms-builder` or the conflicting dependency out of
        # `setup.py` and install it separately, to avoid the runtime dependency
        # check.
    ],
    scripts=[
        'foo.py',
    ],
)
```

And the script:

```python
print 'foo'
```

The above example works, because I am overriding the sub-dependency with an explicit top-level dependency that exactly matches `django-forms-builder`. If I remove that explicit top-level dependency, I get this error, because `0.15.2` gets installed:

```bash
(venv)$ foo.py
Traceback (most recent call last):
  File "/Users/tailee/.virtualenvs/foo/bin/foo.py", line 4, in <module>
    __import__('pkg_resources').require('foo==0.1')
  File "/Users/tailee/.virtualenvs/foo/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/Users/tailee/.virtualenvs/foo/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/Users/tailee/.virtualenvs/foo/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/tailee/.virtualenvs/foo/lib/python2.7/site-packages/pkg_resources/__init__.py", line 653, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/tailee/.virtualenvs/foo/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/tailee/.virtualenvs/foo/lib/python2.7/site-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'future==0.15.0' distribution was not found and is required by django-forms-builder
```

If I swap the order and put `django-forms-builder` before `django-fluent-pages`, it works again. However, if `django-fluent-pages` required a version that was mutually exclusive, e.g. `<0.15.0` or `>0.15.0` or `==0.15.2`, this conflict would be literally impossible to resolve in `setup.py` and I would have to completely remove one of the two packages from `setup.py` and install it separately, so it doesn't register as a dependency of my package when the script is executed.

`django-forms-builder` should not be imposing these restrictions on projects that want to use it along side other packages that also require `future` (especially as it is a commonly required package), when it doesn't even actually require a specific version of `future`. It previously worked fine with `0.9.0` and it seems it works fine now with `0.15.0`.

Again, `setup.py` should only include minimum and maximum version specifications when the package actually requires features (introduced in a minimum version number) or is known not to work (with changes introduced in a maximum version number). You even do this with `Django` already.

**Comment by stephenmcd** [comment]
I didn't get a chance to read everything you wrote (sorry!), but to be clear, all my previous comments were intended to be against the idea of allowing newer versions of a dependency to be installed without them first having been tested. That definitely still stands and always will, but the dependency certainly doesn't need to be an exact version, so I've changed the requirement to `future <= 0.15.0` in ed4622d3a3f2750426d4eb3dc96885cf9d4c33f8

Good luck!

**Comment by mrmachine** [comment]
This doesn't really resolve the problem. As noted above, even if you include an absolute or maximum version number, `pip` resolves nested dependencies in "first found, wins" order.

So if my project depends on something (for example `django-fluent-contents`) which depends `future`, `pip` will install the version specified by `django-fluent-contents` and completely ignore the version you have specified in `django-forms-builder`, because `django-fluent-contents` happens to be listed first in my project's `setup.py` (because I happen to sort the dependencies).

Most other packages (like `django-fluent-contents`) will include the minimum version for their dependencies, and `future` is a common dependency for a lot of packages, and so `pip` will actually very frequently install the latest version regardless of what you specify.

So, your package cannot prevent future versions being installed, but your package will prevent my project from installing scripts that work because of the strict dependency version checking that happens at runtime.

If `django-forms-builder` was a standalone project that you just installed and ran on its own, only needing its own dependencies, that would be understandable that you wouldn't want it deployed with untested future versions of dependencies. But it's not a project, it's a package that gets installed into other projects, and you have no idea what other dependencies that project will have. If `future==0.15.2` has a feature that my project needs, `django-forms-builder` makes it unecessarily difficult to integrate with my project.

**Pull request closed without merging**
